"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/languages/nfd-wonder-blocks.pot",
    "translation": "/languages/nfd-wonder-blocks-%locale%.po",
      "languages_mapping": {
         "locale": {
            "de": "de_DE",
            "en-AU": "en_AU",
            "en-GB": "en_GB",
            "es-ES": "es_ES",
            "fr": "fr_FR",
            "it": "it_IT",
            "nl": "nl_NL"
         }
      }
  }
]